### ISSUE TITLE
Provided signature does not match calculated signature.

### ISSUE THREAD

**Issue by aboullaite** [messenger4j/messenger4j-spring-boot-quickstart-template#1]
Hi,

I followed all the required steps, but I always got the error Processing of callback payload failed: Signature verification failed. Provided signature does not match calculated signature.

**Comment by maxgrabenhorst** [comment]
Hi,

please make sure that your configured App Secret matches the App Secret of your FB app (which is linked to your FB page).

**Comment by aboullaite** [comment]
My bad. Thank you :)
