### ISSUE TITLE
getstarted button 

### ISSUE THREAD

**Issue by mokrane1989** [messenger4j/messenger4j-spring-boot-quickstart-template#17]
i Work on messenger4j Spring boot chabot , and i want to implement a get started button

**Comment by maxgrabenhorst** [comment]
please take a look at the messenger4j readme: https://github.com/messenger4j/messenger4j

**Comment by mokrane1989** [comment]
i Work on messenger4j Spring boot chabot , and i want to implement a get started button

**Comment by mokrane1989** [comment]
i Work on messenger4j Spring boot chabot , and i want to implement a get started button
