### ISSUE TITLE
Upgrade to messenger4j 1.0.0-M3

### ISSUE THREAD

**Issue by maxgrabenhorst** [messenger4j/messenger4j-spring-boot-quickstart-template#19]
I need assistance in upgrading this quickstart project to the latest version of messenger4j.
There is already a branch (integration_m4j_1_0_0). The first changes have been made.
In the first step it would be great to port the existing features to the current version.
Afterwards new features could be implemented (NLP, ...).

**Comment by xcapdevila** [comment]
@maxgrabenhorst I've completed the migration of the existing features and I'll submit a PR

**Comment by maxgrabenhorst** [comment]
Thank you so much @xcapdevila!
I merged everything to master and released the final version.
