### ISSUE TITLE
MessagePayload.create

### ISSUE THREAD

**Issue by izhidov** [messenger4j/messenger4j-spring-boot-quickstart-template#23]
MessagePayload.create requires MessagingType parameter but is omitted in the sample code. There was another API difference. Is messenger4j 1.0.0 API current?

**Comment by izhidov** [comment]
Btw, thank you for updating Spring Boot Quickstart!

**Comment by maxgrabenhorst** [comment]
Thanks for reporting!
I've fixed it now on master.
Version 1.0.0 ist the latest version.
