### ISSUE TITLE
Do not receive callback from Messenger

### ISSUE THREAD

**Issue by apovn** [messenger4j/messenger4j-spring-boot-quickstart-template#24]
I setup my FB app, switch it to Live mode.
![image](https://user-images.githubusercontent.com/15623657/45741685-6ab5a800-bc22-11e8-9fae-5ebe5d082b00.png)

And I config callback URL:
![image](https://user-images.githubusercontent.com/15623657/45741799-b700e800-bc22-11e8-8f8b-00cc0c755cb5.png)

When I click "Verify and Save" button. I received a callback from FB messenger successfully.

But when I access my FB page: https://www.facebook.com/speedupbiz/
by a individual FB account (it is not an account that I use to create this FB page), I click "Send message" button. 
=> Result: I do not receive any call back from Messenger, it doesn't call to handleCallback() method in 
MessengerPlatformCallbackHandler.java

Anyone has the same problem ? Is it a bug ?

**Comment by MechOrigin** [comment]
I have the same problem. Idk how to go about solving it yet. Any clues?

Edit:

Go to your app in facebook developer:
To fix this change your API version -> Settings -> Advanced -> Upgrade API Settings to v2.11 (default is 2.10 I think)

This worked for me.
