### ISSUE TITLE
Error in docs?

### ISSUE THREAD

**Issue by roschler** [messenger4j/messenger4j-spring-boot-quickstart-template#6]
Hi,

The docs say that the file *application.properties* is found in this directory:

"The configuration is located in src/resources/application.properties."

But I pulled the latest repo and it's actually in the directory shown below, and not in the stated directory at all:

src/main/resources/application.properties.

**Comment by maxgrabenhorst** [comment]
Hi, thanks for reporting this issue.
If you like you can create a pull request to fix that. Otherwise I will change this with the next update :)

**Comment by roschler** [comment]
Hi Max,

I've been really busy so I didn't see your "pull request" not.  Sorry.
