### ISSUE TITLE
Welcome message and get started button 

### ISSUE THREAD

**Issue by veyselpehlivan** [messenger4j/messenger4j-spring-boot-quickstart-template#7]
Hi,
 
How to setup a welcome message and start button?  You do not explain in tutorial.

Thanks

**Comment by veyselpehlivan** [comment]
For welcome message, you should use MessengerSetupClient class. For get started button, you should use SetupResponse class. Create objects from these classes. After that add pageAccessToken as a parameter to constructor of MessengerPlatformCallbackHandler class. Lastly, add this code to constructor of MessengerPlatformCallbackHandler class.

```
this.setupClient=MessengerPlatform.newSetupClientBuilder(accessToken).build();
this.setupClient.setupWelcomeMessage("This is the starting point. Click to get started");

this.setupResponse= this.setupClient.setupStartButton("get started");

```

**Comment by mokrane1989** [comment]
more explain please
