### ISSUE TITLE
quick reply buttons

### ISSUE THREAD

**Issue by veyselpehlivan** [messenger4j/messenger4j-spring-boot-quickstart-template#8]
Hello,

I want to make quick reply button without text. I tried but there is no method for this. Could you make method that only sending quick reply button?

Thanks

**Comment by maxgrabenhorst** [comment]
Hi, this is not supported by the Messenger Platform API. You have to provide a text when sending a quick reply button. If still required I recommend to file a feature request on the FB Messenger Platform.
